### ISSUE TITLE
Comments fail to load

### ISSUE THREAD

**Issue by lol768** [bishopmatthew/HackerNews#90]
Using v2.1.8, all comments on all submissions cause a "Couldn't connect to Hacker News" error and a suggestion to check the network connection and try again.

Logcat shows this:

    02-15 01:01:59.512 W/ResourceType(2219): No package identifier when getting value for resource number 0x00000000

    02-15 01:01:59.512 W/PackageManager(2219): Failure retrieving resources for com.airlocksoftware.hackernews: Resource ID #0x0

Any idea what might be going wrong? I'm running the ParanoidAndroid alpha ROM on hammerhead (android 5.0.2). As far as I'm aware this has only recent become a problem.

**Comment by fny** [comment]
I started seeing this about 3 days ago too. I'm using an old Galaxy Nexus with the stock ROM.

**Comment by bishopmatthew** [comment]
Thanks guys, I'm working on it this morning -- you should see a fix roll out later today.

**Comment by bishopmatthew** [comment]
Fixed in bef5d1fc0d8fce2a5ac39612c3800aaaf2250287, rolling out on the Play Store now. Cheers!
