### ISSUE TITLE
Comments no longer viewable?

### ISSUE THREAD

**Issue by lol768** [bishopmatthew/HackerNews#92]
Recently it seems I can only read the articles - the comment tab doesn't appear, nor do the counts next to each article.

**Comment by scottopell** [comment]
Also having this issue

**Comment by SikhNerd** [comment]
Ditto

**Comment by daphreak** [comment]
Affects me as well. Now goes straight to article where before it went to comments first.

**Comment by Thieum** [comment]
+1

**Comment by lol768** [comment]
I have a feeling it's this chunk of code being executed https://github.com/bishopmatthew/HackerNews/blob/master/src/com/airlocksoftware/hackernews/parser/StoryParser.java#L227-234

I'll try and see if I can get it to load in an IDE and have a play with the code. Shame I can't just vim it and run a build command.

**Comment by alexandernyquist** [comment]
Happens for me as well, but only on the front page.

Will try to see if I can fix it later, but I also had some troubles setting up the environment.

**Comment by Jesse-Millwood** [comment]
Also happening with me

**Comment by bishopmatthew** [comment]
Sorry for not being on top of this; I've had a bunch of family in town and
haven't had a chance to look at what's going on yet. They probably just
rearranged some html. I'll try to fix it tomorrow.

**Comment by bishopmatthew** [comment]
Fixed in c2a709bf274b88458a9c6a9be758438d6bfc7867, and rolling out on the Play Store.

**Comment by lol768** [comment]
Thanks a ton :)

**Comment by Jesse-Millwood** [comment]
Thanks for the quick response!
