### ISSUE TITLE
Comments show as deleted

### ISSUE THREAD

**Issue by Everlag** [bishopmatthew/HackerNews#94]
When opening a thread, all comments appear in what seem to be the correct place but have content and author set to 'deleted'.

This happens on both my Nexus 4 and Oneplus 3.

**Comment by seldonPlan** [comment]
I can confirm, this is happening on my Nexus 6 as well

**Comment by sjorsbranderhorst** [comment]
I can confirm, same behaviour on samsung s5 mini.

**Comment by zgkaos** [comment]
I confirm the same is happening on Lg G3.

**Comment by Everlag** [comment]
Thanks for the confirmations, I believe HN's html changed.

[This is](https://github.com/bishopmatthew/HackerNews/blob/d0b041e075885e0d8e8bd1e552d92e956b92ea22/src/com/airlocksoftware/hackernews/parser/CommentsParser.java#L188) probably where the issue happens,  I'll play with the element selectors used in the app to see if there's a quick fix.

**Comment by Everlag** [comment]
Change looks like span to a div, PR #95

**Comment by Everlag** [comment]
Merged, thanks @bishopmatthew!

**Comment by bishopmatthew** [comment]
Rolling it out to the store now.

Thanks @Everlag
